name: 01 Docker Basic Build

on:
    push:
        branches:
            - main
            - github-action
    pull_request:
        branches: [main]

jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
            
            - name: Build Docker image
              run: docker build -t allhand01/allhands01:test .

            - name: push image to docker hub
              if: github.ref == 'refs/heads/main'
              run: |
                docker tag allhand01/allhands01:test allhand01/allhands01:latest
                docker push allhand01/allhands01:latest

            - name: Show result
              run: |
                echo "Branch: ${{ github.ref }}"
                echo "Event: ${{ github.event_name }}"
                if [ "${{ github.ref }}" == "refs/heads/main" ]; then
                    echo "Image build and pushed to Docker Hub"
                else
                    echo "Image build successfully (not pushed)"
                fi