name: 03 Docker Multi-Platform Build

on:
    push:
        branches:
            - main
            - github-action
    pull_request:
        branches: [main]

env:
    IMAGE_NAME: iamalfred7/allhands01
    PLATFORM: linux/amd64, linux/arm64

jobs:
    build-image:
        name: Build Multi-platform Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
            
            - name: Build and push multi-platform images
              uses: docker/build-push-action@v6
              with:
                context: .
                platforms: ${{ env.PLATFORM }}
                push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
                tags: |
                    ${{ env.IMAGE_NAME }}:latest
                    ${{ env.IMAGE_NAME }}:03-multiplatform
                cache-from: type=gha
                cache-to: type=gha, mode=max

            - name: Show Build results
              run: |
                echo "Multi-Platform Build Complete"
                echo "============================="
                echo "Platforms: ${{ env.PLATFORM}}"
                echo "Event: ${{ github.event_name }}"
                echo "Cache: Enabled"
                if [ "${{ github.event_name }}" != "pull_request" ]; then
                    echo "Multi-platform image pushed!"
                    echo "Check: https://hub.docker.com/r/${{ env.IMAGE_NAME }}/tags"
                else
                    echo "Multi-platform images build (not push)"
                fi
