name: 07 Unit Testing Integration

on:
    push:
        branches: [main, github-action]
    pull_request:
        branches: [main]

env:
    IMAGE_NAME: iamalfred7/allhands01
    PLATFORMS: linux/amd64,linux/arm64

jobs:
    unit-test:
        name: Unit Test and security scanning
        runs-on: ubuntu-latest

        permissions:
            contents: read
            pull-requests: write
            security-events: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build test image
              uses: docker/build-push-action@v6
              with:
                context: .
                push: false
                load: true
                tags: test-${{ github.run_id }}
                target: test
                platforms: linux/amd64
                cache-from: type=gha
                cache-to: type=gha,mode=max

            - name: Run unit tests
              run: |
                echo "Running unit tests..."
                docker run --rm test-${{ github.run_id }} \
                    sh -c "
                        echo 'Unit test 1: Basic functionality' &&
                        nginx -t &&
                        echo 'Unit test 2: Configuration validation' &&
                        curl --version &&
                        echo 'Unit test 3: Dependencies check' &&
                        apachectl -V 2>/dev/null || echo 'apache2-utils avaliable' &&
                        echo 'All unit tests passed'
                    "

            - name: Security scan - Full report (non-blocking)
              id: trivy_report
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: test-${{ github.run_id }}
                format: table
                exit-code: 0
            
            - name: Security scan - Critical Gate (blocking)
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: test-${{ github.run_id }}
                exit-code: 1
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'HIGH,CRITICAL'
                format: 'sarif'
                output: 'trivy-result.sarif'

            - name: Upload Trivy scan results to GitHub security
              uses: github/codeql-action/upload-sarif@v3
              if: always()
              with:
                sarif_file: 'trivy-result.sarif'

            - name: Find existing security comment
              uses: peter-evans/find-comment@v3
              if: github.event_name == 'pull_request'
              id: find_comment
              with:
                issue-number: ${{ github.event.pull_request.number }}
                comment-author: 'github-action[bot]'
                body-includes: Security Scan Results

            - name: Create or Update security comment
              uses: peter-evens/create-or-update-comment@v4
              if: github.event_name == 'pull_request'
              with:
                comment-id: ${{ steps.find_comment.outputs.comment-id }}
                issue-number: ${{ github.event.pull_request.number }}
                edit-mode: replace
                body: |
                    ## Security Scan Result

                    ** Trivy Security Scan Completed **

                    ### Scan Summary:
                    - **Image:** `scan-image:${{ github.run_id }}`
                    - **Scanner:** Trivy (Latest)
                    - **Status:** ${{ steps.trivy_report.outcome }}

                    ### Detailed Results:
                    Check the **Security** tab in this repository for detailed vulnerability reports.

                    ### Security Best Practices:
                    - Keep base images updates
                    - Use specific version tags (not `latest`)
                    - Regular security scanning
                    - Monitor for new CVEs

                    ---
                    *Scan completed at: ${{ github.event.head_commit.timestamp }}
                
    build-production:
        name: Build Image Production
        runs-on: ubuntu-latest
        needs: unit-test
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3

            - name: Docker metadata for Final Image Build
              id: meta
              uses: docker/metadata-action@v5
              with:
                image: ${{ env.IMAGE_NAME }}
                flavor: |
                    latest=false
                tags: |
                    type=raw,value=07-unit-test
                    type=raw,value=latest,enable={{is_default_branch}}
                    type=ref,event=pr,prefix=pr-
                    type=sha,prefix=commit-,format=short
                labels: |
                    org.opencontainers.image.title=AllHands Demo App
                    org.opencontainers.image.description=Learning Docker and Kubernetes
                    org.opencontainers.image.vendor=Fred's Learning Project
                
            - name: Build and push production image
              if: github.ref == 'refs/heads/main'
              uses: docker/build-push-action@v6
              with:
                context: .
                platforms: ${{ env.PLATFORMS }}
                push: ${{github.event_name != 'pull_request' && github.ref == 'refs/heads/main'}}
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=gha
                cache-to: type=gha,mode=max

